"""add_auth_identities_and_nullable_pw

Revision ID: 5e733905616f
Revises: 1b45ab85df62
Create Date: 2026-04-14 07:28:14.802331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e733905616f'
down_revision: Union[str, Sequence[str], None] = '1b45ab85df62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('provider_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_auth_identities_provider_provider_user_id')
    )
    op.create_index(op.f('ix_auth_identities_provider_user_id'), 'auth_identities', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id_expires_at'), table_name='password_reset_tokens')
    op.alter_column('users', 'hashed_pw',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_pw',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id_expires_at'), 'password_reset_tokens', ['user_id', 'expires_at'], unique=False)
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_provider_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    # ### end Alembic commands ###
